### ISSUE TITLE
inconsistent results result with the paper

### ISSUE THREAD

**Issue by youshyee** [zwyang6/SeCo#1]
Thanks for sharing the code.
I managed to run your code but the result I get is quite different from the ones in the paper.

|- | CAM | val |
|---|---|---|
|training result| 73.6| 71.8|
|paper result| 74.8 | 74.0 |

Here is my training log:
[train.log](https://github.com/zwyang6/SeCo/files/14495363/train.log)

**Comment by zwyang6** [comment]
Thanks for your attention! 

The results of CAMs and Masks in our paper are evaluated on the VOC train set. The semantic performance is evaluated on the val set and DenseCRF is used as the post-processing. 

The generated log file only records the results from val set and no post-processing applied. Hope it could help you.

**Comment by zwyang6** [comment]
> Thanks for sharing the code. I managed to run your code but the result I get is quite different from the ones in the paper.
> 
> -	CAM	val
> training result	73.6	71.8
> paper result	74.8	74.0
> Here is my training log: [train.log](https://github.com/zwyang6/SeCo/files/14495363/train.log)

BTW, this is the reproduced  log when i sort the code recently. Please take a check. 
[train.log](https://github.com/zwyang6/SeCo/files/14495703/train.log)
