### ISSUE TITLE
weight problem

### ISSUE THREAD

**Issue by Queliot** [zwyang6/SeCo#10]
Hi！thank you very much for your outstanding work. I'm encountering a strange issue while trying to reproduce your code. Initially, the mIoU is around 27%, and then it suddenly drops to 10% after 10,000 iterations. I'm sure I downloaded the pretrained weights, but something seems to be wrong. Also, it seems that the weight files provided in the code do not have permission for download.

**Comment by zwyang6** [comment]
Thansk for your attention ! Please strickly follow our codes and the requirements.txt file. I  have produced many times, SeCo demonstrates consistent performance. 

I will make the checkpoints publicly available again. You can download it.

**Comment by Queliot** [comment]
Thanks!!! U are so kind!
