### ISSUE TITLE
fully-supervised counterparts

### ISSUE THREAD

**Issue by tnwls6865** [zwyang6/SeCo#2]
Hello! Thank you for your interest in our work on WSSS and for your kind words.

When I read your paper, I became curious about Table 5, which compares the fully-supervised counterparts in the paper. 
How did you train the fully-supervised counterparts? 
Did you experiment by changing pseudo-labels into ground truth masks?

Thanks!

**Comment by zwyang6** [comment]
Thanks for your attention ! 

We leverage the ground truth masks from voc to train the fully-supervised counterparts.

Actually, there are many researches already implemented such experiment, such as [AFA](https://openaccess.thecvf.com/content/CVPR2022/papers/Ru_Learning_Affinity_From_Attention_End-to-End_Weakly-Supervised_Semantic_Segmentation_With_Transformers_CVPR_2022_paper.pdf) and [WeaTr](https://arxiv.org/pdf/2304.01184.pdf).

**Comment by geek-APTX4869** [comment]
能提供下全监督的权重吗，或者怎么得到表5的结果，想学习一下

**Comment by zwyang6** [comment]
> 能提供下全监督的权重吗，或者怎么得到表5的结果，想学习一下

你好 请参考[ToCo] https://arxiv.org/pdf/2303.01267 表3
