### ISSUE TITLE
adaptive prototype updating

### ISSUE THREAD

**Issue by minju-Kang** [zwyang6/SeCo#4]
Thank you for sharing your works!
I have question about adaptive prototype updating for multi-class images.

https://github.com/zwyang6/SeCo/blob/17508084980b47d952af1527bf6e635186097fc2/model/model_seco.py#L61
In this code, it seems the prototype is updated only by the single class images.
However in the paper (Section 3.4), you mention that cosine similarity of the class token and corresponding prototype is used as the weight to estimate the relevance of corresponding category.

I would appreciate if you could tell me where the code of the adaptive prototype updating for multi-class images is.
Thanks.

**Comment by zwyang6** [comment]
Thank you for your attention and kind reminding. 

In our raw manuscript, the cls prototypes are only updated with single cls images to maintain the correctness. With the simple similarity weight, now we can also leverage the information from multi-cls token while maintaining the performance. 

We will update the codes very soon.

**Comment by xd-429** [comment]
> Thank you for your attention and kind reminding.
> 
> In our raw manuscript, the cls prototypes are only updated with single cls images to maintain the correctness. With the simple similarity weight, now we can also leverage the information from multi-cls token while maintaining the performance.
> 
> We will update the codes very soon.

您提到可以在保持性能的前提下利用多 cls 标记的信息，请问相关代码在哪里呢

**Comment by wxqlab** [comment]
Dear author,

Have you updated the code? How can I resolve this issue regarding the multi-class cls token update the image category knowledge?
