### ISSUE TITLE
Issues related to CAM (74.8) and Mask (76.5) evaluation indicators

### ISSUE THREAD

**Issue by tt-lucky8** [zwyang6/SeCo#5]
Thank you for sharing the code. I would like to know how the results of CAM (74.8) and Mask (76.5) were evaluated. Is CAM the result of CAM in the log?Is Mask the result of pseudo labels?  but I can't see any relevant data in the log, and I can't find  code to evaluate Mask results. I am seeking your advice and look forward to your reply.
﻿

**Comment by zwyang6** [comment]
Thank for your attention!
 The log files provided only record the results w/o post-processing. To reproduce the results in the table, you can evaluate the provided checkpoints with ./tools/evaluate_cam.py. We will update the relevant code soon.

**Comment by zwyang6** [comment]
> Thank you for sharing the code. I would like to know how the results of CAM (74.8) and Mask (76.5) were evaluated. Is CAM the result of CAM in the log?Is Mask the result of pseudo labels? but I can't see any relevant data in the log, and I can't find code to evaluate Mask results. I am seeking your advice and look forward to your reply.

The code is available at ./tools/infer_cam.py. If you find it helpful, your star is sincerely appreciated !

**Comment by geek-APTX4869** [comment]
cannot import name 'get_valid_cam' from 'utils.camutils'

**Comment by zwyang6** [comment]
> cannot import name 'get_valid_cam' from 'utils.camutils'

您好，代码已更新
https://github.com/zwyang6/SeCo/blob/202357f1f97b349bcd8d7d54664eca2978619608/utils/camutils.py#L225

觉得有帮助的话麻烦多多引用与STAR ^_^
