### ISSUE TITLE
有关于上Coco推理结果的一些问题

### ISSUE THREAD

**Issue by Minorant** [zwyang6/SeCo#9]
作者您好！我想知道您在coco上最终结果是val_part的结果还是整个val的结果，因为我注意到在coco_train.log中用的是val_part的结果，我在A6000上复现测得在整个val上的结果是43.4（log结果），低于coco_train.log的结果。
以及最终的结果是否有用到crf，因为我在用crf的时候发现每一张图片会产生70-110MB不等大小的.npz文件，最终整个文件夹会达到3.3T，并且多尺度推理+后处理要花费几乎一天的时间，结果相对于原来甚至还掉点了，这是否是正常现象？
感谢您的工作，也期待您的回复！

**Comment by zwyang6** [comment]
你好！ 我们提供的训练文件是val_part的验证结果。如您所试验的，训练过程中如果验证整个val set 会极大地增加训练时间。在single-stage 的wsss范式中一般均采取此策略， 如ToCo, DuPL等工作。

SeCo是在两张3090上进行训练的，大概训练了2-3天左右。多尺度+crf后处理确实会耗费很久的时间，而且由于crf的需求，同样会产生很大的npz文件。我们是采用一张3090，大概也是验证了1天时间。

就我们的多次实验发现，一般后处理会提高大概1-2点左右，所以您可以仔细检查以下代码以及我们所提供的环境进行配置。如果您觉得训练时间以及推理时间很长的话，可以增加训练或者推理的卡数进行多卡并行运算。

希望对您有帮助。

**Comment by zwyang6** [comment]
您好，我帮你排除了一下关于推理文件存储空间过大的问题：原因是我们将seg插值到gt原始大小存储的。
请看  https://github.com/zwyang6/SeCo/blob/bfbea02c2174209fdd6871bf3f90957ba1f6a53b/tools/infer_seg_coco.py#L84

您可以将其插值到标签大小的0.2倍左右进行存储，CRF时再统一插值到标签大小可以显著减小存储空间。
如果有帮助的话，麻烦多多引用以及给个STAR ^_^

**Comment by Minorant** [comment]
感谢您的回复，基本上之前的问题都得到解决！
btw还有一个小小问题想问一下，paper Table 1 (a)表的CAM是否指的是在train set中仅翻转增强的CAM图
Mask是在train set中翻转增强 + 多尺度的CAM图？

**Comment by zwyang6** [comment]
是的， CAM seeds 直接将推理文件中的scale list 改成[1.0]即可。 Mask 指的是 flip+multi-scale+ CRF 后的结果。
